name: Docker Image CI

on:
  push:
    branches: ["main"]
env:
  VERSION: "0.1.9"
  PROJECT_ID: hybrid-robot-375813
  GCE_INSTANCE: dykim-g5 # instance name
  GCE_INSTANCE_ZONE: us-west1-b # instance zone

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: google auth
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCE_SA_KEY }}"

      - name: set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: use gcloud cli
        run: "gcloud info"

      - name: gcp deploy
        run: |-
          gcloud compute instances update-container "${{ env.GCE_INSTANCE }}"" \
            --zone "${{ env.GCE_INSTANCE_ZONE }}"" \
            --container-image "dongyoungkim/home:${{ env.VERSION }}"
